name: openstack-compute-api
version: 0
summary: OpenStack Compute API
description: OpenStack Compute API
confinement: devmode

apps:
  nova-api-os-compute:
    command: bin/run.sh nova-api-os-compute
    daemon: simple
    plugs:
      - network-bind
      - network
  nova-manage:
    command: bin/run.sh nova-manage
    plugs:
      - network
  nova-rootwrap:
    command: bin/run.sh nova-rootwrap
    plugs:
      - network

parts:
  nova:
    plugin: python3
    source: https://github.com/openstack/nova
    source-type: git
    source-branch: stable/mitaka
    build-packages: [python3-dev, libssl-dev, libxml2-dev, libxslt1-dev, pkg-config,
                     libffi-dev, libpq-dev, libmysqlclient-dev, graphviz, libsqlite3-dev]
  config:
    plugin: copy
    files:
      ../../../parts/nova/src/etc/nova/api-paste.ini: etc/nova/
      ../../../parts/nova/src/etc/nova/rootwrap.conf: etc/nova/
      ../../../parts/nova/src/etc/nova/policy.json: etc/nova/
      ../../../parts/nova/src/etc/nova/rootwrap.d/*: etc/nova/rootwrap.d/
      etc/nova.conf: etc/nova/nova.conf
      templates/*: templates/
      bin/run.sh: bin/run.sh
