name: openstack-compute-controller
version: 0
summary: OpenStack Compute Controller
description: OpenStack Compute API
confinement: strict

apps:
  nova-api-os-compute:
    command: bin/run.sh nova-api-os-compute
    daemon: simple
    plugs:
      - network-bind
      - network
  nova-conductor:
    command: bin/run.sh nova-conductor
    daemon: simple
    plugs:
      - network
  nova-scheduler:
    command: bin/run.sh nova-scheduler
    daemon: simple
    plugs:
      - network
  nova-manage:
    command: bin/run.sh nova-manage
    plugs:
      - network
      - network-bind

parts:
  nova:
    plugin: python3
    source: http://tarballs.openstack.org/nova/nova-stable-mitaka.tar.gz
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/mitaka/upper-constraints.txt
    build-packages: [python3-dev, libssl-dev, libxml2-dev, libxslt1-dev, pkg-config,
                     libffi-dev, libpq-dev, libmysqlclient-dev, graphviz, libsqlite3-dev]
  config:
    plugin: copy
    files:
      ../../../parts/nova/src/etc/nova/api-paste.ini: etc/nova/
      ../../../parts/nova/src/etc/nova/rootwrap.conf: etc/nova/
      ../../../parts/nova/src/etc/nova/policy.json: etc/nova/
      ../../../parts/nova/src/etc/nova/rootwrap.d/*: etc/nova/rootwrap.d/
      etc/nova.conf: etc/nova/nova.conf
      templates/*: templates/
      bin/run.sh: bin/run.sh
